line1: "这是示范MOTD的第一行"
line2: "这是示范MOTD的第二行"

players:
  # 最大玩家数量显示，不填则采用BC配置。
  max: 512

  # 统计玩家数量的服务器配置
  count:
    type: NAME # 通过名字匹配
    servers: # 来源的服务器，留空则代表全服
      - "lobby"

  # 玩家数的二次计算方式，默认为IDENTITY，即不计算。
  math: IDENTITY

  # 玩家数量栏的样式
  # 当鼠标放到玩家数量栏上时，提示框中的内容
  # 留空则使用默认样式
  samples:
    - "这是示范消息的第一行"

protocol:
  name: "这是示范协议的名称" # 协议名称，留空则采用BC配置
  version: 0 # 协议版本号，留空或<=0则采用BC配置

# 显示的服务器模组类型，可选 FML / BUKKIT / VANILLA
mod-type: FML

# 服务器图片的名称，请将原图放置在插件配置文件夹中的icons文件夹内
icon: "/icons/example.png"

# 域名匹配表；配置后将根据玩家使用的服务器域名来显示对应的消息
# 留空后，玩家使用的域名未匹配任何限定内容时，将显示该内容。
hostnames:
  - "*.example.com"