line1: "这是示范MOTD的第一行"
line2: "这是示范MOTD的第二行"

players:
  # 最大玩家数量显示，不填则采用BC配置。
  max: 512

  # 玩家数的二次计算方式，默认为IDENTITY，即不计算。
  # 可选：IDENTITY(原始), MULTIPLE:<倍数>，DYNAMIC(动态增加), ZERO(不显示玩家数量)
  math: IDENTITY

  # 玩家数量栏的样式
  # 当鼠标放到玩家数量栏上时，提示框中的内容
  # 留空则使用默认样式
  samples:
    - "这是示范消息的第一行"

protocol:
  name: "这是示范协议的名称" # 协议名称，留空则采用BC配置
  version: 0 # 协议版本号，留空或<=0则采用BC配置

# 显示的服务器模组类型，可选 FML / BUKKIT / VANILLA
mod-type: VANILLA

# 服务器图片的名称，请将原图放置在插件配置文件夹中的favicons文件夹内
favicon: "example.png"

# 域名正则匹配表，配置后将根据玩家使用的服务器域名来显示对应的消息。
# 留空后，玩家使用的域名未匹配任何限定内容时，将显示该内容。
hostnames:
  - "[a-z0-9-]+\.example\.com"